apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-nestjs
spec:
  selector:
    matchLabels:
      app: ms-nestjs
  template:
    metadata:
      labels:
        app: ms-nestjs
    spec:
      containers:
        - name: ms-nestjs
          image: jdnielss/ms-nestjs
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 10
          env:
            - name: DATABASE_HOST
              value: 'mysql'
            - name: DATABASE_PORT
              value: '3306'
            - name: DATABASE_USER
              value: 'root'
            - name: DATABASE_PASSWORD
              value: 'password'
          resources:
            requests:
              cpu: 250m
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-nestjs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-nestjs
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Min
      stabilizationWindowSeconds: 120
---
apiVersion: v1
kind: Service
metadata:
  name: ms-nestjs
spec:
  selector:
    app: ms-nestjs
  ports:
    - protocol: TCP
      port: 3000
  type: LoadBalancer
